# Sample body segment definitions for scale calibration
# This file defines standard body segment lengths for an average adult

[segments]
# Full height measurements (from heel to head), height minus 0.12m which is the average distance of Nose to the top of head
height_right = { keypoint1 = "RHeel", keypoint2 = "Nose", length = 1.63 }
height_left = { keypoint1 = "LHeel", keypoint2 = "Nose", length = 1.63 }

# Arm measurements
arm_upper_right = { keypoint1 = "RShoulder", keypoint2 = "RElbow", length = 0.33 }
arm_upper_left = { keypoint1 = "LShoulder", keypoint2 = "LElbow", length = 0.33 }
forearm_right = { keypoint1 = "RElbow", keypoint2 = "RWrist", length = 0.27 }
forearm_left = { keypoint1 = "LElbow", keypoint2 = "LWrist", length = 0.27 }

# Leg measurements
thigh_right = { keypoint1 = "RHip", keypoint2 = "RKnee", length = 0.42 }
thigh_left = { keypoint1 = "LHip", keypoint2 = "LKnee", length = 0.42 }
shin_right = { keypoint1 = "RKnee", keypoint2 = "RAnkle", length = 0.43 }
shin_left = { keypoint1 = "LKnee", keypoint2 = "LAnkle", length = 0.43 }

# Torso measurements
shoulder_width = { keypoint1 = "RShoulder", keypoint2 = "LShoulder", length = 0.41 }
trunk_length = { keypoint1 = "Neck", keypoint2 = "CHip", length = 0.53 }